apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: {{ include "daprmq.fullname" . }}-dapr-config
  labels:
    {{- include "daprmq.labels" . | nindent 4 }}
spec:
  tracing:
    samplingRate: "1"
  # Enable actor reentrancy for better concurrency
  features:
    - name: Actor.Reentrancy
      enabled: true
