# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import daprmq_pb2 as daprmq__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in daprmq_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DaprMQStub:
    """DaprMQ service provides FIFO queue operations with priority support,
    acknowledgment-based message handling, and lock management.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Enqueue = channel.unary_unary(
                '/daprmq.DaprMQ/Enqueue',
                request_serializer=daprmq__pb2.EnqueueRequest.SerializeToString,
                response_deserializer=daprmq__pb2.EnqueueResponse.FromString,
                _registered_method=True)
        self.Dequeue = channel.unary_unary(
                '/daprmq.DaprMQ/Dequeue',
                request_serializer=daprmq__pb2.DequeueRequest.SerializeToString,
                response_deserializer=daprmq__pb2.DequeueResponse.FromString,
                _registered_method=True)
        self.DequeueLocked = channel.unary_unary(
                '/daprmq.DaprMQ/DequeueLocked',
                request_serializer=daprmq__pb2.DequeueLockedRequest.SerializeToString,
                response_deserializer=daprmq__pb2.DequeueLockedResponse.FromString,
                _registered_method=True)
        self.Acknowledge = channel.unary_unary(
                '/daprmq.DaprMQ/Acknowledge',
                request_serializer=daprmq__pb2.AcknowledgeRequest.SerializeToString,
                response_deserializer=daprmq__pb2.AcknowledgeResponse.FromString,
                _registered_method=True)
        self.ExtendLock = channel.unary_unary(
                '/daprmq.DaprMQ/ExtendLock',
                request_serializer=daprmq__pb2.ExtendLockRequest.SerializeToString,
                response_deserializer=daprmq__pb2.ExtendLockResponse.FromString,
                _registered_method=True)
        self.DeadLetter = channel.unary_unary(
                '/daprmq.DaprMQ/DeadLetter',
                request_serializer=daprmq__pb2.DeadLetterRequest.SerializeToString,
                response_deserializer=daprmq__pb2.DeadLetterResponse.FromString,
                _registered_method=True)
        self.AcceptSession = channel.unary_unary(
                '/daprmq.DaprMQ/AcceptSession',
                request_serializer=daprmq__pb2.AcceptSessionRequest.SerializeToString,
                response_deserializer=daprmq__pb2.AcceptSessionResponse.FromString,
                _registered_method=True)
        self.RenewSessionLease = channel.unary_unary(
                '/daprmq.DaprMQ/RenewSessionLease',
                request_serializer=daprmq__pb2.RenewSessionLeaseRequest.SerializeToString,
                response_deserializer=daprmq__pb2.RenewSessionLeaseResponse.FromString,
                _registered_method=True)
        self.ReleaseSession = channel.unary_unary(
                '/daprmq.DaprMQ/ReleaseSession',
                request_serializer=daprmq__pb2.ReleaseSessionRequest.SerializeToString,
                response_deserializer=daprmq__pb2.ReleaseSessionResponse.FromString,
                _registered_method=True)
        self.ConsumeSession = channel.stream_stream(
                '/daprmq.DaprMQ/ConsumeSession',
                request_serializer=daprmq__pb2.ConsumeSessionRequest.SerializeToString,
                response_deserializer=daprmq__pb2.ConsumeSessionResponse.FromString,
                _registered_method=True)


class DaprMQServicer:
    """DaprMQ service provides FIFO queue operations with priority support,
    acknowledgment-based message handling, and lock management.
    """

    def Enqueue(self, request, context):
        """Enqueue an item to the queue with optional priority.
        Priority 0 is the fast lane, priority 1 (default) is normal processing.
        Lower priority numbers are processed first.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Dequeue(self, request, context):
        """Dequeue one or more items from the queue without acknowledgment.
        Returns immediately if queue is empty or items are locked.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DequeueLocked(self, request, context):
        """Dequeue one or more items from the queue with acknowledgment.
        Creates locks with TTL and returns lock_ids for acknowledgment.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Acknowledge(self, request, context):
        """Acknowledge and permanently remove a locked item from the queue.
        Requires valid lock_id from DequeueLocked.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtendLock(self, request, context):
        """Extend the TTL of an existing lock.
        Useful for long-running processing that needs more time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeadLetter(self, request, context):
        """Move a locked item to the dead letter queue and void the lock.
        Used when a message cannot be processed successfully after multiple attempts.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptSession(self, request, context):
        """Claim exclusive ownership of a session - "any available" (session_id unset) or targeted
        (session_id set, sticky routing). Once claimed, Dequeue/DequeueLocked/Acknowledge/ExtendLock/
        DeadLetter are called against "{queue_id}-session-{session_id}" with lease_id set.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenewSessionLease(self, request, context):
        """Heartbeat to keep an already-claimed session lease alive past what would otherwise be its
        expiry.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseSession(self, request, context):
        """Explicitly give up a claimed session lease, freeing it for another consumer immediately
        rather than waiting out the lease TTL. Idempotent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsumeSession(self, request_iterator, context):
        """Managed consume loop for exactly one session per call: claims a session (any-available or
        targeted), streams delivered items back, accepts Ack/DeadLetter, and renews the lease on the
        server's own schedule for as long as the stream stays open - no client heartbeat needed. On
        disconnect the server releases the session immediately, faster than the lease TTL would.
        One stream = one session (see plan §2.4.1) - a client wanting N concurrent sessions opens N
        of these streams, which multiplex cheaply over one gRPC channel/HTTP2 connection.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DaprMQServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Enqueue': grpc.unary_unary_rpc_method_handler(
                    servicer.Enqueue,
                    request_deserializer=daprmq__pb2.EnqueueRequest.FromString,
                    response_serializer=daprmq__pb2.EnqueueResponse.SerializeToString,
            ),
            'Dequeue': grpc.unary_unary_rpc_method_handler(
                    servicer.Dequeue,
                    request_deserializer=daprmq__pb2.DequeueRequest.FromString,
                    response_serializer=daprmq__pb2.DequeueResponse.SerializeToString,
            ),
            'DequeueLocked': grpc.unary_unary_rpc_method_handler(
                    servicer.DequeueLocked,
                    request_deserializer=daprmq__pb2.DequeueLockedRequest.FromString,
                    response_serializer=daprmq__pb2.DequeueLockedResponse.SerializeToString,
            ),
            'Acknowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.Acknowledge,
                    request_deserializer=daprmq__pb2.AcknowledgeRequest.FromString,
                    response_serializer=daprmq__pb2.AcknowledgeResponse.SerializeToString,
            ),
            'ExtendLock': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtendLock,
                    request_deserializer=daprmq__pb2.ExtendLockRequest.FromString,
                    response_serializer=daprmq__pb2.ExtendLockResponse.SerializeToString,
            ),
            'DeadLetter': grpc.unary_unary_rpc_method_handler(
                    servicer.DeadLetter,
                    request_deserializer=daprmq__pb2.DeadLetterRequest.FromString,
                    response_serializer=daprmq__pb2.DeadLetterResponse.SerializeToString,
            ),
            'AcceptSession': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptSession,
                    request_deserializer=daprmq__pb2.AcceptSessionRequest.FromString,
                    response_serializer=daprmq__pb2.AcceptSessionResponse.SerializeToString,
            ),
            'RenewSessionLease': grpc.unary_unary_rpc_method_handler(
                    servicer.RenewSessionLease,
                    request_deserializer=daprmq__pb2.RenewSessionLeaseRequest.FromString,
                    response_serializer=daprmq__pb2.RenewSessionLeaseResponse.SerializeToString,
            ),
            'ReleaseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseSession,
                    request_deserializer=daprmq__pb2.ReleaseSessionRequest.FromString,
                    response_serializer=daprmq__pb2.ReleaseSessionResponse.SerializeToString,
            ),
            'ConsumeSession': grpc.stream_stream_rpc_method_handler(
                    servicer.ConsumeSession,
                    request_deserializer=daprmq__pb2.ConsumeSessionRequest.FromString,
                    response_serializer=daprmq__pb2.ConsumeSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'daprmq.DaprMQ', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('daprmq.DaprMQ', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DaprMQ:
    """DaprMQ service provides FIFO queue operations with priority support,
    acknowledgment-based message handling, and lock management.
    """

    @staticmethod
    def Enqueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daprmq.DaprMQ/Enqueue',
            daprmq__pb2.EnqueueRequest.SerializeToString,
            daprmq__pb2.EnqueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Dequeue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daprmq.DaprMQ/Dequeue',
            daprmq__pb2.DequeueRequest.SerializeToString,
            daprmq__pb2.DequeueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DequeueLocked(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daprmq.DaprMQ/DequeueLocked',
            daprmq__pb2.DequeueLockedRequest.SerializeToString,
            daprmq__pb2.DequeueLockedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Acknowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daprmq.DaprMQ/Acknowledge',
            daprmq__pb2.AcknowledgeRequest.SerializeToString,
            daprmq__pb2.AcknowledgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtendLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daprmq.DaprMQ/ExtendLock',
            daprmq__pb2.ExtendLockRequest.SerializeToString,
            daprmq__pb2.ExtendLockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeadLetter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daprmq.DaprMQ/DeadLetter',
            daprmq__pb2.DeadLetterRequest.SerializeToString,
            daprmq__pb2.DeadLetterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcceptSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daprmq.DaprMQ/AcceptSession',
            daprmq__pb2.AcceptSessionRequest.SerializeToString,
            daprmq__pb2.AcceptSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenewSessionLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daprmq.DaprMQ/RenewSessionLease',
            daprmq__pb2.RenewSessionLeaseRequest.SerializeToString,
            daprmq__pb2.RenewSessionLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daprmq.DaprMQ/ReleaseSession',
            daprmq__pb2.ReleaseSessionRequest.SerializeToString,
            daprmq__pb2.ReleaseSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsumeSession(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/daprmq.DaprMQ/ConsumeSession',
            daprmq__pb2.ConsumeSessionRequest.SerializeToString,
            daprmq__pb2.ConsumeSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
