// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: daprmq.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DaprMQ_Enqueue_FullMethodName           = "/daprmq.DaprMQ/Enqueue"
	DaprMQ_Dequeue_FullMethodName           = "/daprmq.DaprMQ/Dequeue"
	DaprMQ_DequeueLocked_FullMethodName     = "/daprmq.DaprMQ/DequeueLocked"
	DaprMQ_Acknowledge_FullMethodName       = "/daprmq.DaprMQ/Acknowledge"
	DaprMQ_AcknowledgeBatch_FullMethodName  = "/daprmq.DaprMQ/AcknowledgeBatch"
	DaprMQ_Nack_FullMethodName              = "/daprmq.DaprMQ/Nack"
	DaprMQ_ExtendLock_FullMethodName        = "/daprmq.DaprMQ/ExtendLock"
	DaprMQ_DeadLetter_FullMethodName        = "/daprmq.DaprMQ/DeadLetter"
	DaprMQ_AcceptSession_FullMethodName     = "/daprmq.DaprMQ/AcceptSession"
	DaprMQ_RenewSessionLease_FullMethodName = "/daprmq.DaprMQ/RenewSessionLease"
	DaprMQ_ReleaseSession_FullMethodName    = "/daprmq.DaprMQ/ReleaseSession"
	DaprMQ_ConsumeSession_FullMethodName    = "/daprmq.DaprMQ/ConsumeSession"
)

// DaprMQClient is the client API for DaprMQ service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DaprMQ service provides FIFO queue operations with priority support,
// acknowledgment-based message handling, and lock management.
type DaprMQClient interface {
	// Enqueue an item to the queue with optional priority.
	// Priority 0 is the fast lane, priority 1 (default) is normal processing.
	// Lower priority numbers are processed first.
	Enqueue(ctx context.Context, in *EnqueueRequest, opts ...grpc.CallOption) (*EnqueueResponse, error)
	// Dequeue one or more items from the queue without acknowledgment.
	// Returns immediately if queue is empty or items are locked.
	Dequeue(ctx context.Context, in *DequeueRequest, opts ...grpc.CallOption) (*DequeueResponse, error)
	// Dequeue one or more items from the queue with acknowledgment.
	// Creates locks with TTL and returns lock_ids for acknowledgment.
	DequeueLocked(ctx context.Context, in *DequeueLockedRequest, opts ...grpc.CallOption) (*DequeueLockedResponse, error)
	// Acknowledge and permanently remove a locked item from the queue.
	// Requires valid lock_id from DequeueLocked.
	Acknowledge(ctx context.Context, in *AcknowledgeRequest, opts ...grpc.CallOption) (*AcknowledgeResponse, error)
	// Acknowledge up to 1,000 locks in one call, with an outcome per lock. Succeeds whenever the
	// request is valid; read each result's outcome. Safe to re-send: locks an earlier attempt settled
	// come back LOCK_NOT_FOUND.
	AcknowledgeBatch(ctx context.Context, in *AcknowledgeBatchRequest, opts ...grpc.CallOption) (*AcknowledgeBatchResponse, error)
	// Return a locked item to its original position in the queue and void the lock. Counts as a
	// delivery attempt: past the server's max delivery count the item is dead-lettered instead.
	Nack(ctx context.Context, in *NackRequest, opts ...grpc.CallOption) (*NackResponse, error)
	// Extend the TTL of an existing lock.
	// Useful for long-running processing that needs more time.
	ExtendLock(ctx context.Context, in *ExtendLockRequest, opts ...grpc.CallOption) (*ExtendLockResponse, error)
	// Move a locked item to the dead letter queue and void the lock.
	// Used when a message cannot be processed successfully after multiple attempts.
	DeadLetter(ctx context.Context, in *DeadLetterRequest, opts ...grpc.CallOption) (*DeadLetterResponse, error)
	// Claim exclusive ownership of a session - "any available" (session_id unset) or targeted
	// (session_id set, sticky routing). Once claimed, Dequeue/DequeueLocked/Acknowledge/ExtendLock/
	// DeadLetter are called against "{queue_id}-session-{session_id}" with lease_id set.
	AcceptSession(ctx context.Context, in *AcceptSessionRequest, opts ...grpc.CallOption) (*AcceptSessionResponse, error)
	// Heartbeat to keep an already-claimed session lease alive past what would otherwise be its
	// expiry.
	RenewSessionLease(ctx context.Context, in *RenewSessionLeaseRequest, opts ...grpc.CallOption) (*RenewSessionLeaseResponse, error)
	// Explicitly give up a claimed session lease, freeing it for another consumer immediately
	// rather than waiting out the lease TTL. Idempotent.
	ReleaseSession(ctx context.Context, in *ReleaseSessionRequest, opts ...grpc.CallOption) (*ReleaseSessionResponse, error)
	// Managed consume loop for exactly one session per call: claims a session (any-available or
	// targeted), streams delivered items back, accepts Ack/DeadLetter/Nack, and renews the lease on the
	// server's own schedule for as long as the stream stays open - no client heartbeat needed. On
	// disconnect the server releases the session immediately, faster than the lease TTL would.
	// One stream = one session (see plan §2.4.1) - a client wanting N concurrent sessions opens N
	// of these streams, which multiplex cheaply over one gRPC channel/HTTP2 connection.
	ConsumeSession(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConsumeSessionRequest, ConsumeSessionResponse], error)
}

type daprMQClient struct {
	cc grpc.ClientConnInterface
}

func NewDaprMQClient(cc grpc.ClientConnInterface) DaprMQClient {
	return &daprMQClient{cc}
}

func (c *daprMQClient) Enqueue(ctx context.Context, in *EnqueueRequest, opts ...grpc.CallOption) (*EnqueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnqueueResponse)
	err := c.cc.Invoke(ctx, DaprMQ_Enqueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daprMQClient) Dequeue(ctx context.Context, in *DequeueRequest, opts ...grpc.CallOption) (*DequeueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DequeueResponse)
	err := c.cc.Invoke(ctx, DaprMQ_Dequeue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daprMQClient) DequeueLocked(ctx context.Context, in *DequeueLockedRequest, opts ...grpc.CallOption) (*DequeueLockedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DequeueLockedResponse)
	err := c.cc.Invoke(ctx, DaprMQ_DequeueLocked_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daprMQClient) Acknowledge(ctx context.Context, in *AcknowledgeRequest, opts ...grpc.CallOption) (*AcknowledgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcknowledgeResponse)
	err := c.cc.Invoke(ctx, DaprMQ_Acknowledge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daprMQClient) AcknowledgeBatch(ctx context.Context, in *AcknowledgeBatchRequest, opts ...grpc.CallOption) (*AcknowledgeBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcknowledgeBatchResponse)
	err := c.cc.Invoke(ctx, DaprMQ_AcknowledgeBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daprMQClient) Nack(ctx context.Context, in *NackRequest, opts ...grpc.CallOption) (*NackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NackResponse)
	err := c.cc.Invoke(ctx, DaprMQ_Nack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daprMQClient) ExtendLock(ctx context.Context, in *ExtendLockRequest, opts ...grpc.CallOption) (*ExtendLockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtendLockResponse)
	err := c.cc.Invoke(ctx, DaprMQ_ExtendLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daprMQClient) DeadLetter(ctx context.Context, in *DeadLetterRequest, opts ...grpc.CallOption) (*DeadLetterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeadLetterResponse)
	err := c.cc.Invoke(ctx, DaprMQ_DeadLetter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daprMQClient) AcceptSession(ctx context.Context, in *AcceptSessionRequest, opts ...grpc.CallOption) (*AcceptSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptSessionResponse)
	err := c.cc.Invoke(ctx, DaprMQ_AcceptSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daprMQClient) RenewSessionLease(ctx context.Context, in *RenewSessionLeaseRequest, opts ...grpc.CallOption) (*RenewSessionLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewSessionLeaseResponse)
	err := c.cc.Invoke(ctx, DaprMQ_RenewSessionLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daprMQClient) ReleaseSession(ctx context.Context, in *ReleaseSessionRequest, opts ...grpc.CallOption) (*ReleaseSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseSessionResponse)
	err := c.cc.Invoke(ctx, DaprMQ_ReleaseSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daprMQClient) ConsumeSession(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConsumeSessionRequest, ConsumeSessionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DaprMQ_ServiceDesc.Streams[0], DaprMQ_ConsumeSession_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConsumeSessionRequest, ConsumeSessionResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaprMQ_ConsumeSessionClient = grpc.BidiStreamingClient[ConsumeSessionRequest, ConsumeSessionResponse]

// DaprMQServer is the server API for DaprMQ service.
// All implementations must embed UnimplementedDaprMQServer
// for forward compatibility.
//
// DaprMQ service provides FIFO queue operations with priority support,
// acknowledgment-based message handling, and lock management.
type DaprMQServer interface {
	// Enqueue an item to the queue with optional priority.
	// Priority 0 is the fast lane, priority 1 (default) is normal processing.
	// Lower priority numbers are processed first.
	Enqueue(context.Context, *EnqueueRequest) (*EnqueueResponse, error)
	// Dequeue one or more items from the queue without acknowledgment.
	// Returns immediately if queue is empty or items are locked.
	Dequeue(context.Context, *DequeueRequest) (*DequeueResponse, error)
	// Dequeue one or more items from the queue with acknowledgment.
	// Creates locks with TTL and returns lock_ids for acknowledgment.
	DequeueLocked(context.Context, *DequeueLockedRequest) (*DequeueLockedResponse, error)
	// Acknowledge and permanently remove a locked item from the queue.
	// Requires valid lock_id from DequeueLocked.
	Acknowledge(context.Context, *AcknowledgeRequest) (*AcknowledgeResponse, error)
	// Acknowledge up to 1,000 locks in one call, with an outcome per lock. Succeeds whenever the
	// request is valid; read each result's outcome. Safe to re-send: locks an earlier attempt settled
	// come back LOCK_NOT_FOUND.
	AcknowledgeBatch(context.Context, *AcknowledgeBatchRequest) (*AcknowledgeBatchResponse, error)
	// Return a locked item to its original position in the queue and void the lock. Counts as a
	// delivery attempt: past the server's max delivery count the item is dead-lettered instead.
	Nack(context.Context, *NackRequest) (*NackResponse, error)
	// Extend the TTL of an existing lock.
	// Useful for long-running processing that needs more time.
	ExtendLock(context.Context, *ExtendLockRequest) (*ExtendLockResponse, error)
	// Move a locked item to the dead letter queue and void the lock.
	// Used when a message cannot be processed successfully after multiple attempts.
	DeadLetter(context.Context, *DeadLetterRequest) (*DeadLetterResponse, error)
	// Claim exclusive ownership of a session - "any available" (session_id unset) or targeted
	// (session_id set, sticky routing). Once claimed, Dequeue/DequeueLocked/Acknowledge/ExtendLock/
	// DeadLetter are called against "{queue_id}-session-{session_id}" with lease_id set.
	AcceptSession(context.Context, *AcceptSessionRequest) (*AcceptSessionResponse, error)
	// Heartbeat to keep an already-claimed session lease alive past what would otherwise be its
	// expiry.
	RenewSessionLease(context.Context, *RenewSessionLeaseRequest) (*RenewSessionLeaseResponse, error)
	// Explicitly give up a claimed session lease, freeing it for another consumer immediately
	// rather than waiting out the lease TTL. Idempotent.
	ReleaseSession(context.Context, *ReleaseSessionRequest) (*ReleaseSessionResponse, error)
	// Managed consume loop for exactly one session per call: claims a session (any-available or
	// targeted), streams delivered items back, accepts Ack/DeadLetter/Nack, and renews the lease on the
	// server's own schedule for as long as the stream stays open - no client heartbeat needed. On
	// disconnect the server releases the session immediately, faster than the lease TTL would.
	// One stream = one session (see plan §2.4.1) - a client wanting N concurrent sessions opens N
	// of these streams, which multiplex cheaply over one gRPC channel/HTTP2 connection.
	ConsumeSession(grpc.BidiStreamingServer[ConsumeSessionRequest, ConsumeSessionResponse]) error
	mustEmbedUnimplementedDaprMQServer()
}

// UnimplementedDaprMQServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDaprMQServer struct{}

func (UnimplementedDaprMQServer) Enqueue(context.Context, *EnqueueRequest) (*EnqueueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enqueue not implemented")
}
func (UnimplementedDaprMQServer) Dequeue(context.Context, *DequeueRequest) (*DequeueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Dequeue not implemented")
}
func (UnimplementedDaprMQServer) DequeueLocked(context.Context, *DequeueLockedRequest) (*DequeueLockedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DequeueLocked not implemented")
}
func (UnimplementedDaprMQServer) Acknowledge(context.Context, *AcknowledgeRequest) (*AcknowledgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Acknowledge not implemented")
}
func (UnimplementedDaprMQServer) AcknowledgeBatch(context.Context, *AcknowledgeBatchRequest) (*AcknowledgeBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcknowledgeBatch not implemented")
}
func (UnimplementedDaprMQServer) Nack(context.Context, *NackRequest) (*NackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Nack not implemented")
}
func (UnimplementedDaprMQServer) ExtendLock(context.Context, *ExtendLockRequest) (*ExtendLockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtendLock not implemented")
}
func (UnimplementedDaprMQServer) DeadLetter(context.Context, *DeadLetterRequest) (*DeadLetterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeadLetter not implemented")
}
func (UnimplementedDaprMQServer) AcceptSession(context.Context, *AcceptSessionRequest) (*AcceptSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptSession not implemented")
}
func (UnimplementedDaprMQServer) RenewSessionLease(context.Context, *RenewSessionLeaseRequest) (*RenewSessionLeaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewSessionLease not implemented")
}
func (UnimplementedDaprMQServer) ReleaseSession(context.Context, *ReleaseSessionRequest) (*ReleaseSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseSession not implemented")
}
func (UnimplementedDaprMQServer) ConsumeSession(grpc.BidiStreamingServer[ConsumeSessionRequest, ConsumeSessionResponse]) error {
	return status.Error(codes.Unimplemented, "method ConsumeSession not implemented")
}
func (UnimplementedDaprMQServer) mustEmbedUnimplementedDaprMQServer() {}
func (UnimplementedDaprMQServer) testEmbeddedByValue()                {}

// UnsafeDaprMQServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DaprMQServer will
// result in compilation errors.
type UnsafeDaprMQServer interface {
	mustEmbedUnimplementedDaprMQServer()
}

func RegisterDaprMQServer(s grpc.ServiceRegistrar, srv DaprMQServer) {
	// If the following call panics, it indicates UnimplementedDaprMQServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DaprMQ_ServiceDesc, srv)
}

func _DaprMQ_Enqueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaprMQServer).Enqueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaprMQ_Enqueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaprMQServer).Enqueue(ctx, req.(*EnqueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaprMQ_Dequeue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DequeueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaprMQServer).Dequeue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaprMQ_Dequeue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaprMQServer).Dequeue(ctx, req.(*DequeueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaprMQ_DequeueLocked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DequeueLockedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaprMQServer).DequeueLocked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaprMQ_DequeueLocked_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaprMQServer).DequeueLocked(ctx, req.(*DequeueLockedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaprMQ_Acknowledge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaprMQServer).Acknowledge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaprMQ_Acknowledge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaprMQServer).Acknowledge(ctx, req.(*AcknowledgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaprMQ_AcknowledgeBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaprMQServer).AcknowledgeBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaprMQ_AcknowledgeBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaprMQServer).AcknowledgeBatch(ctx, req.(*AcknowledgeBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaprMQ_Nack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaprMQServer).Nack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaprMQ_Nack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaprMQServer).Nack(ctx, req.(*NackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaprMQ_ExtendLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtendLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaprMQServer).ExtendLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaprMQ_ExtendLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaprMQServer).ExtendLock(ctx, req.(*ExtendLockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaprMQ_DeadLetter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeadLetterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaprMQServer).DeadLetter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaprMQ_DeadLetter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaprMQServer).DeadLetter(ctx, req.(*DeadLetterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaprMQ_AcceptSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaprMQServer).AcceptSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaprMQ_AcceptSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaprMQServer).AcceptSession(ctx, req.(*AcceptSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaprMQ_RenewSessionLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewSessionLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaprMQServer).RenewSessionLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaprMQ_RenewSessionLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaprMQServer).RenewSessionLease(ctx, req.(*RenewSessionLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaprMQ_ReleaseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaprMQServer).ReleaseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaprMQ_ReleaseSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaprMQServer).ReleaseSession(ctx, req.(*ReleaseSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaprMQ_ConsumeSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DaprMQServer).ConsumeSession(&grpc.GenericServerStream[ConsumeSessionRequest, ConsumeSessionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaprMQ_ConsumeSessionServer = grpc.BidiStreamingServer[ConsumeSessionRequest, ConsumeSessionResponse]

// DaprMQ_ServiceDesc is the grpc.ServiceDesc for DaprMQ service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DaprMQ_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "daprmq.DaprMQ",
	HandlerType: (*DaprMQServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enqueue",
			Handler:    _DaprMQ_Enqueue_Handler,
		},
		{
			MethodName: "Dequeue",
			Handler:    _DaprMQ_Dequeue_Handler,
		},
		{
			MethodName: "DequeueLocked",
			Handler:    _DaprMQ_DequeueLocked_Handler,
		},
		{
			MethodName: "Acknowledge",
			Handler:    _DaprMQ_Acknowledge_Handler,
		},
		{
			MethodName: "AcknowledgeBatch",
			Handler:    _DaprMQ_AcknowledgeBatch_Handler,
		},
		{
			MethodName: "Nack",
			Handler:    _DaprMQ_Nack_Handler,
		},
		{
			MethodName: "ExtendLock",
			Handler:    _DaprMQ_ExtendLock_Handler,
		},
		{
			MethodName: "DeadLetter",
			Handler:    _DaprMQ_DeadLetter_Handler,
		},
		{
			MethodName: "AcceptSession",
			Handler:    _DaprMQ_AcceptSession_Handler,
		},
		{
			MethodName: "RenewSessionLease",
			Handler:    _DaprMQ_RenewSessionLease_Handler,
		},
		{
			MethodName: "ReleaseSession",
			Handler:    _DaprMQ_ReleaseSession_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ConsumeSession",
			Handler:       _DaprMQ_ConsumeSession_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "daprmq.proto",
}
