apiVersion: v1
kind: Service
metadata:
  name: daprmq-example
  labels:
    app: daprmq-example
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: daprmq-example
